{
    volScalarField rAU("rAU", 1.0/UEqn.A());
    surfaceScalarField rAUf("rAUf", fvc::interpolate(rAU));
    volVectorField HbyA(constrainHbyA(rAU*UEqn.H(), U, p_rgh));

    // buoyancy/“gravity” flux term (Boussinesq)
    surfaceScalarField phig(-rAUf*ghf*fvc::snGrad(rhok)*mesh.magSf());

    surfaceScalarField phiHbyA
    (
        "phiHbyA",
          fvc::flux(HbyA)
        + rAUf*fvc::ddtCorr(U, phi)
        + phig
    );

    // Ensure pressure BCs are consistent with flux formulation
    constrainPressure(p_rgh, U, phiHbyA, rAUf);

    while (pimple.correctNonOrthogonal())
    {
        fvScalarMatrix p_rghEqn
        (
            fvm::laplacian(rAUf, p_rgh) == fvc::div(phiHbyA)
        );

        p_rghEqn.solve(p_rgh.select(pimple.finalInnerIter()));

        if (pimple.finalNonOrthogonalIter())
        {
            // Conservative fluxes from pressure solve
            phi = phiHbyA - p_rghEqn.flux();

            // Relax p_rgh before momentum correction
            p_rgh.relax();

            // Momentum correction with relaxed pressure gradient
            U = HbyA + rAU*fvc::reconstruct((phig - p_rghEqn.flux())/rAUf);
            U.correctBoundaryConditions();
            fvOptions.correct(U);

        }
    }

    #include "continuityErrs.H"

}
